---
title: "Can a city's walkability score predict it's future?"
format: 
  html:
    code-fold: true
editor: visual
---

## Overview of data

make a map

```{r include=FALSE}
library(tidyverse)
#import cleaned data from SQL and Census
source("~/gvsu/summer 23/stat 631/Collection/sections/dataviz/map/import_clean_merge.R")
#import cleaned data
#Import cleaned data from SQL and Census
# source("~/map/import_clean_merge.R")

# map areas
my_state <-  'MI'
my_county <-  c("Kent", "Ottawa", "Allegan", "Barry", "Eaton", "Oceana", 
                "Barry", "Muskegon", "Newaygo", "Ionia", "Montcalm", "Mecosta",
                "Ingham", "Gratiot", "Clinton", "Isabella")

roads_data <-  primary_secondary_roads(my_state) %>% 
  filter(RTTYP %in% c('U','S','I')) #this will limit the roads to just highways. 

landmass_data <-  counties(cb = TRUE, state = my_state) %>%
  filter(NAME %in% my_county)

water_data <-  area_water(my_state, my_county)

# Ensure the CRS for all objects are the same before performing spatial operations
map_area <-  st_crs(near_kent)

roads_data <- st_transform(roads_data, map_area)
landmass_data <- st_transform(landmass_data, map_area)
water_data <- st_transform(water_data, map_area)
```


```{r}
gr_map <- ggplot() +
  theme_void()  + #whiteout
  # blank gray map
  geom_sf(data = landmass_data, fill = '#e6e6e6', color = NA,aes(geometry = geometry))+
  #add walkability scores
  geom_sf(data = wlk_gr, color = NA, aes(geometry = geometry, fill = NatWalkInd))+
  #add water
  geom_sf(data = water_data, fill = '#cce6ff',color = NA, aes(geometry = geometry)) +
  #add roads
  geom_sf(data = roads_data, color = 'white', aes(geometry = geometry))


# creates coordinates around the geographic area for a zoomed in map!
limits = st_bbox(wlk_gr$geometry)


gr_map <-  gr_map + 
  coord_sf(xlim = c(as.numeric(limits$xmin),as.numeric(limits$xmax)), 
           ylim = c(as.numeric(limits$ymin),as.numeric(limits$ymax))) +
  labs(fill = 'Walkability Index',
  title =  "Walkability in the Greater Grand Rapids Area",
  caption = "Source: 'The Walkability Index' | US Environmental Protection Agency") + 
  # move legend to bottom left
  theme(legend.justification = c(0,0), legend.position = c(0.1,0.1)) + 
  scale_fill_gradient(low = '#F1FCAE', high = '#184F50')

gr_map
ggsave(filename = "map.png", plot = gr_map, dpi = 300)
#hey that's a decent map :-) 
```


###### inspired by Matt Bartholomew's "[Making a Better Map](https://bartholomatt.net/posts/census_maps_part2/), ggplot and Tigris"
