---
title: "explore the data"
---

install packages, and import data

```{r}
source("~/gvsu/summer 23/stat 631/portfolio/Website/sections/dataviz/map/import_clean_merge.R")
```

```{r}
wlk_data <-  wlk_mi %>% 
  select(GEOID.x, NatWalkInd, COUNTYFP, CBSA_Name, TRACTCE) %>% 
  mutate(CTRACT = paste0(COUNTYFP, TRACTCE))
  
```

```{r}
summary(wlk_data$NatWalkInd)
```

```{r}
ggplot(wlk_data, aes(x = NatWalkInd)) +
  geom_histogram(binwidth = 1, fill = "#3F4D55", color = "white")

```

```{r}
ggplot(wlk_data, aes(x = CBSA_Name, y = NatWalkInd, fill = CBSA_Name)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "CBSA", y = "NatWalkInd", title = "Boxplot of NatWalkInd by CBSA") +
  theme(legend.position = "none") # remove legend if it is not needed

```

```{r}
wlk_gr <- wlk_data %>% 
  filter(CBSA_Name == "Grand Rapids-Kentwood, MI")

wlk_gr %>% 
ggplot(aes(x = CBSA_Name, y = NatWalkInd, fill = COUNTYFP)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "County", y = "NatWalkInd", title = "Boxplot of NatWalkInd by CBSA") +
  theme(legend.position = "none") # remove legend if it is not needed

```

```{r}
colnames(wlk_mi)
```

```{r}

# Ensure your data is in a simple features object
wlk_data_sf <- st_as_sf(wlk_data)

# Plot
ggplot() +
  geom_sf(data = wlk_data_sf, aes(fill = NatWalkInd)) +
  scale_fill_viridis_c()  # or another suitable colour scale

```

```{r}
wlk_gr  %>% 
ggplot() +
  geom_sf(aes(fill = NatWalkInd)) +
  scale_fill_viridis_c() +
  theme(
    panel.background = element_blank(),   # remove the background
    panel.grid = element_blank(),         # remove the grid
    axis.text = element_blank(),          # remove axis labels
    axis.ticks = element_blank(),         # remove axis ticks
    axis.title = element_blank()          # remove axis titles
  )
```

```{r}
wlk_gr %>% 
ggplot(aes(x = NatWalkInd, y = factor(COUNTYFP), color = factor(COUNTYFP))) +
  geom_jitter(height = 0.2, width = 0.2) +
  labs(x = "NatWalkInd Score", y = "County", color = "County") +
  ggtitle("NatWalkInd Scores by County") +
  theme_minimal()
```

```{r}
ggplot(wlk_gr, aes(x = NatWalkInd, y = factor(COUNTYFP), color = factor(COUNTYFP))) +
  geom_jitter(height = 0.2, width = 0.2) +
  labs(x = "NatWalkInd Score", y = "County", color = "County") +
  ggtitle("NatWalkInd Scores by County") 
```

```{r}
wlk_county <-  wlk_data %>% 
  group_by(COUNTYFP) %>% 
  summarise(county_wlk_index = median(NatWalkInd))
```

```{r}
attach(wlk_data)
plot(NatWalkInd)
```

