project:
  type: website
  output-dir: docs

website:
  title: Brooke Walter's Portfolio
  page-navigation: true
  site-url: https://brookemwalters.github.io/Collection/
  favicon: "images/logos/favicon2.png"
  open-graph: true


  page-footer:
    right: "This page is built with ☕ and [Quarto](https://quarto.org/)."
    background: "#FEFAF2"
  
  sidebar:
    background: "#FEFAF2"
    logo: "images/logos/logo1.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/BrookemWalters/collection
        text: "gitHub organization"
      - icon: linkedin
        href: https://www.linkedin.com/in/bmwlters
        text: "LinkedIn"
      - icon: person-fill
        text: "pitch"
        menu:
          - text: about me
            href: index.qmd
          - text: interactive positionality statement
            href: sections/reflections/sop.qmd

    
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Projects"
        contents:
          - href: sections/po.qmd
            text: "Overview"
          - href: sections/glmv1/pi.qmd
            text: "Time Series Forecasting"
          - href: https://brookemwalters.github.io/Nimby_Site/Final%20Report.html
            text: "Crime in Coloardo"
      - section: "Reflections"
        contents:
          - href: sections/reflections/reflections_main.qmd
            text: "Collection of reflections"
          - href: sections/reflections/knowledge/knowledge.qmd
            text: "Knowledge"
      - href: sections/references/resources.qmd
        text: "Resources"



  
format:
  html:
    smooth-scroll: true
    theme: journal
    css: styles.css
    link-external-newwindow: true
    code-background: true
    code-copy: true



freeze: auto
editor: visual  
  

    
    
    
 