project:
  type: website
  output-dir: docs

website:
  title: Brooke Walter's Portfolio
  page-navigation: true
  site-url: https://brookemwalters.github.io/Collection/
  favicon: "images/logos/favicon1.png"
  open-graph: true
  
  repo-url: https://github.com/BrookemWalters/Collection
  repo-actions: [edit, issue]

  page-footer:
    right: "This page is built with ☕ and [Quarto](https://quarto.org/)."
    background: "#FEFAF2"
  
  sidebar:
    background: "#FEFAF2"
    logo: "images/logos/logo1.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/BrookemWalters/collection
        text: "gitHub organization"
      - icon: linkedin
        href: https://www.linkedin.com/in/bmwlters
        text: "LinkedIn"
    
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "data viz"
        contents:
          - href: sections/dataviz/viz_placeholder.qmd
            text: "Coming Soon"
      - section: "reflections"
        contents:
          - href: sections/reflections/reflections_main.qmd
            text: "collection of relflections"

  
format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css

  

    
    
    
 