project:
  type: website
  output-dir: docs
  
format:
  html:
    theme:
      light: [journal, theme.scss]
      dark: [cyborg, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true
    back-to-top-navigation: true

freeze: auto
editor: visual  


website:
  title: Brooke Walter's Portfolio
  page-navigation: true
  favicon: "images/logos/favicon1.png"
  open-graph: true

  page-footer:
    right: "This page is built with ☕ and [Quarto](https://quarto.org/)."
    background: "#FEFAF2"
  
  sidebar:
    background: "#FEFAF2"
    logo: "images/logos/logo1.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/BrookemWalters/collection
        text: "gitHub organization"
      - icon: linkedin
        href: https://www.linkedin.com/in/bmwlters
        text: "LinkedIn"
    
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "data viz"
        contents:
          - href: sections/dataviz/viz_placeholder.qmd
            text: "Coming Soon"
      - section: "reflections"
        contents:
          - href: sections/reflections/reflections_main.qmd
            text: guide
          - href: sections/reflections/positionality.qmd
            text: positionality
  



  

    
    
    
 